// File generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli
//      flutterfire configure
// Then replace this file with the generated one from your Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration for each platform.
/// Replace placeholder values with your project credentials from Firebase Console
/// or run `flutterfire configure` to auto-generate this file.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured for this prototype.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkvO8XntXLOhPoEVffJcXMKqENNR2asBc',
    appId: '1:31228850927:android:efc07c3050007e12e3611a',
    messagingSenderId: '31228850927',
    projectId: 'postalapp-afc09',
    storageBucket: 'postalapp-afc09.firebasestorage.app',
  );

  // TODO: Replace with your Firebase iOS app credentials (optional for Android-only prototype).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.postalapp.postalApp',
  );
}
